// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6HFz2Go3S3Ej8y6fY4jfOQQAHurJKxOk',
    appId: '1:959079125882:android:2a0338e85713701017fcc3',
    messagingSenderId: '959079125882',
    projectId: 'liveelhmdaniaa',
    storageBucket: 'liveelhmdaniaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvtbL5W_oku7hkTo6MbTTbO6bjTpCAxv8',
    appId: '1:959079125882:ios:816f9b2b52ec70d417fcc3',
    messagingSenderId: '959079125882',
    projectId: 'liveelhmdaniaa',
    storageBucket: 'liveelhmdaniaa.appspot.com',
    iosClientId: '959079125882-2alh1qhd949fr7fpr8aocfc3f78jk86o.apps.googleusercontent.com',
    iosBundleId: 'com.softwareCloud.live',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvtbL5W_oku7hkTo6MbTTbO6bjTpCAxv8',
    appId: '1:959079125882:ios:83d389c4ddaa38d617fcc3',
    messagingSenderId: '959079125882',
    projectId: 'liveelhmdaniaa',
    storageBucket: 'liveelhmdaniaa.appspot.com',
    iosClientId: '959079125882-bb1b6f3n96mm623oc6j7go5muncr63af.apps.googleusercontent.com',
    iosBundleId: 'y',
  );
}
